version: '2'
services:
  tlog-backend:
    image: trainingproject/tlog16rs
    container_name: tlog-backend
    networks:
    - tlog
    ports:
    - "9080:8080"
    environment:
    - DB_USER=timelogger
    - DB_PASS=633Ym2aZ5b9Wtzh4EJc4pANx
    - DB_URL=jdbc:mariadb://mariadb:3306/timelogger
  mariadb:
    image: mariadb:5.5.51
    container_name: mariadb
    networks:
    - tlog
    volumes:
    - "./database:/var/lib/mysql"
    ports:
    - "9001:3306"
    environment:
    - MYSQL_DATABASE=timelogger
    - MYSQL_USER=timelogger
    - MYSQL_PASSWORD=633Ym2aZ5b9Wtzh4EJc4pANx
    - MYSQL_ROOT_PASSWORD=633Ym2aZ5b9Wtzh4EJc4pANx
  sonarqube:
    image: sonarqube
    container_name: sonarqube
    networks:
    - tlog
    ports:
    - "9000:9000"
    - "9092:9092"
networks:
  tlog:
    driver: bridge