mariadb:
  image: mariadb:5.5.51
  container_name: mariadb
  volumes:
  - "./database:/var/lib/mysql"
  ports:
  - "9001:3306"
  environment:
  - MYSQL_DATABASE=timelogger
  - MYSQL_USER=timelogger
  - MYSQL_PASSWORD=633Ym2aZ5b9Wtzh4EJc4pANx
  - MYSQL_ROOT_PASSWORD=633Ym2aZ5b9Wtzh4EJc4pANx
sonarqube:
  image: sonarqube
  container_name: sonarqube
  ports:
  - "9000:9000"
  - "9092:9092"

